name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      # https://github.com/jupyterlab/maintainer-tools/blob/main/.github/actions/base-setup/action.yml
      with:
        python_version: ${{ matrix.python-version }}
        node_version: '18.x'
    - name: Install dependencies
      run: python -m pip install -U jupyterlab~=4.0
    - name: jlpm config
      run: jlpm config set -H enableImmutableInstalls false
    - name: install ts modules
      run: jlpm
    - name: jlpm lint check
      run: jlpm run eslint:check
    - name: install python package
      run: python -m pip install .
    - name: check for widgyts in extensions
      run: |
        jupyter server extension list 2>&1 | grep -ie "widgyts.*OK"

        jupyter labextension list 2>&1 | grep -ie "@yt-project/yt-widgets.*OK"
    - name: run jupyterlab browser check
      run: python -m jupyterlab.browser_check
